

server:
  port: 8080
  servlet:
    context-path: /rssystem

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seat_reserve_db?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo&allowMultiQueries=true
    username: root
    password: root

    #thymeleaf 設定
    thymeleaf:
        check-template-location: true
        prefix: classpath:/templates/   # .html 呼び出す時の経路(src/main/resources/templates)
        suffix: .html #拡張子
        cache: false
    mvc:
        static-path-pattern: /static/** # spring mvc 静的経路変更
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true    
